![logo](./images/OPTIMISE.%20Logo%20(green).png)

In this project I role play as a BI consultant from Optimise. using Steam as my client. I provide a full sales analysis & a sales prediction model based on key game features.

This is Notebook 3 out of 4 of this project.

# Optimise.
BUSINESS INTELLIGENCE SOLUTIONS

Optimise. uses data analysis to provide businesses a vision of their present operations and provides them with actionable advise based on meticulous analysis that produces tangible results.   

The analysis focuses on these main areas:     
- Product Analysis
    - Performance
    - Classification
    - Pricing
- Customer Analysis
    - Customer Profile
    - Customer Trends
    - Customer Lifetime Value
- Sales Analysis
    - Date/Time Overview
    - Discount Effeciency
    - Projections
    
The deliverables to be expected are a comprehensive report with useful visualizations, combined with specific recommendations based on the results obtained from the analysis.

# Linear Regression Model

The goal of building a linear regression model is to devise a program that can predict the number of sales given certain parameters. For instance if a developer were to launch a `Single-Player`, `Adventure` game with `Controller Support` at a price of $20 how many copies could he expect to sell. 

This tool could be extremely useful for the company and I would like to add it in the package the company would be receiving.

In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as sp
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.utils import resample
from IPython.display import clear_output
from sklearn import metrics
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve

In [8]:
s = pd.read_csv("data/steam_cols_clean.csv")

In [9]:
# grouping boolean columns by type

platforms = ['linux', 'windows', 'mac']
genres = ['Indie', 'Sports', 'Simulation', 'Strategy', 'Early Access', 'Casual',
       'RPG', 'Free to Play', 'Adventure', 'Action', 'Racing']
categories = ['Includes level editor', 'MMO', 'VR Support', 'Single-player',
       'Controller Support', 'Online', 'Multi-Player', 'co-op', 'Local']
tags = ['Nudity', 'Retro', 'Violent', 'Visual Novel', 'RPGMaker', 'Fighting',
       'FPS', 'Female Protagonist', 'Board Game', 'Space', 'World War II',
       'Platformer', 'Anime', 'Great Soundtrack', 'Massively Multiplayer',
       'Open World', 'Sexual Content', 'Arcade', 'Gore', 'Pixel Graphics',
       'Turn-Based', 'Music', 'Fantasy', 'Point & Click', 'Rogue-like',
       'World War I', "Shoot 'Em Up", 'RTS', 'Story Rich', 'Hidden Object',
       'Turn-Based Strategy', 'Survival', 'Match 3', 'Horror', 'Puzzle',
       'Sci-fi', 'Tower Defense', 'VR', 'Management', '2D', 'Card Game',
       'Multiplayer', 'Utilities', 'Shooter', 'War', 'Co-op', 'Zombies',
       'Classic', 'Singleplayer']

In [10]:
s.head(1)

appid            name release_date  english developer publisher  \
0     10  Counter-Strike   2000-11-01        1     Valve     Valve   

   required_age  achievements  positive_ratings  negative_ratings  ...  \
0             0             0            124534              3339  ...   

   Free to Play  Includes level editor VR Support  Single-player  MMO  \
0             0                      0          0              0    0   

   Controller Support  Online  Multi-Player  co-op  Local  
0                   0       1             1      0      1  

[1 rows x 37 columns]

In [5]:
s.columns

Index(['appid', 'name', 'release_date', 'english', 'developer', 'publisher',
       'required_age', 'achievements', 'positive_ratings', 'negative_ratings',
       'average_playtime', 'median_playtime', 'owners', 'price', 'windows',
       'linux', 'mac', 'Strategy', 'Simulation', 'Racing', 'Adventure',
       'Early Access', 'Action', 'Indie', 'Sports', 'RPG', 'Casual',
       'Free to Play', 'Includes level editor', 'VR Support', 'Single-player',
       'MMO', 'Controller Support', 'Online', 'Multi-Player', 'co-op',
       'Local'],
      dtype='object')

### Predicted Number of Sales Given a Certain Price

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

x = s['price'].values.reshape(-1,1)
y = s['owners'].values.reshape(-1,1)

model.fit(x,y)

model.predict(x)

In [ ]:
score = model.score(x,y)
print("R2:", score)

In [ ]:
sns.regplot(x,y)

**Observations:** The R2 score is absolutely minimal which means the model is perfectly inadequate to predict the number of sales based on the price. This makes sense since pricing, whilst important, it's not the biggest distinguishing factor among games nor the beggiest determinant of its purchase. 

This model is therefore useless and I shall have to find a more appropirate way of predicting sales.

# Logistical Regression Model
I will use a logistical regression model since I think it will be more suitable at taking into account categorical data and predicting the amount of sales ranges, which are also categorical in this case.

### Predicted Number of Sales

In [11]:
y = pd.get_dummies(data=s['owners'], drop_first=True)
y.head()

100000-200000  1000000-2000000  10000000-20000000  100000000-200000000  \
0              0                0                  1                    0   
1              0                0                  0                    0   
2              0                0                  0                    0   
3              0                0                  0                    0   
4              0                0                  0                    0   

   20000-50000  200000-500000  2000000-5000000  20000000-50000000  \
0            0              0                0                  0   
1            0              0                0                  0   
2            0              0                0                  0   
3            0              0                0                  0   
4            0              0                0                  0   

   50000-100000  500000-1000000  5000000-10000000  50000000-100000000  
0             0               0                 0                   0  
1             0               0                 1                   0  
2             0               0                 1                   0  
3             0               0                 1                   0  
4             0               0                 1                   0

**Observations:** I can already see that this model might also present its problems, since there's a significantly higher number of games that have between 7.500.000 and 15.000.000 owners, only those 2 categories are represented in the dummies data, which means it will only predecit one of these values. The answer is still valid but the the model wouldn't give us more information than getting the mode of onwers per genre.

In [12]:
s[s["owners"]==7500000].count()[0]/len(s)*100

0.0

**Observations:** Upon closer observation, I realise that in fact not a majority of the games have 7.500.000 owners, which makes me wonder why the dummies reflect that. 

In [13]:
x = pd.get_dummies(data=s[genres], drop_first=True)
x.head()

Indie  Sports  Simulation  Strategy  Early Access  Casual  RPG  \
0      0       0           0         0             0       0    0   
1      0       0           0         0             0       0    0   
2      0       0           0         0             0       0    0   
3      0       0           0         0             0       0    0   
4      0       0           0         0             0       0    0   

   Free to Play  Adventure  Action  Racing  
0             0          0       1       0  
1             0          0       1       0  
2             0          0       1       0  
3             0          0       1       0  
4             0          0       1       0

In [14]:
s["Action"].sum()/len(s)*100

43.963065558633424

**Observations:** Similarly here, the `get_dummies` function seems to be returning interesting results that might affect my model.

#### Approach Number 2
Given the weird results obtained with the `get_dummies` function I have decided to use the data as is instead.

In [15]:
x = s.drop(["appid", "name", "release_date", "developer", "publisher", "owners"], axis=1)
y = s["owners"]

In [16]:
from sklearn.model_selection import train_test_split
 
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [17]:
# first model: logistic regression
from sklearn.linear_model import LogisticRegression
 
log_model = LogisticRegression(max_iter=1000000).fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score

# Get score of the model
score = log_model.score(X_test,y_test)

# Predict using test data
y_pred = log_model.predict(X_test)

# Generate matrix
matrix = confusion_matrix(y_test, y_pred)

print('Accuracy score is:', score)
print('Confusion Matrix:\n',matrix)

Accuracy score is: 0.7508771929824561
Confusion Matrix:
 [[3636    1    0    0    0   66    0    0    0    1    0    0    1]
 [  43   49    1    1    1   96   69    1    1   26    0    0    2]
 [   0    0   13    3    0    0   10    7    0    0   13    1    1]
 [   0    0    0    3    0    0    0    2    0    0    0    1    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0]
 [ 384    7    0    0    0  191    6    0    0   11    1    0    0]
 [  11   31    5    8    1   53  112    6    1    8    8    0    2]
 [   0    0   10    2    0    0    1   18    1    0    5    1    1]
 [   0    0    0    2    0    0    0    0    0    0    0    0    0]
 [ 128   23    0    0    2  147   29    0    0   28    0    0    1]
 [   1   10    7    4    0    6   54    6    0    2   14    1    2]
 [   0    0    2    3    0    0    0    6    0    0    0    2    0]
 [   0    0    0    1    0    0    0    0    0    0    0    0    0]]


In [19]:
# creating a data frame to compare the original and predicted results
compare = {"original" : y_test,
           "predicted" : log_model.predict(X_test)}

c = pd.DataFrame(compare)

c["success"] = np.where(c["original"]==c["predicted"], 1, 0)
c

original      predicted  success
17824        0-20000        0-20000        1
16815        0-20000        0-20000        1
19527    20000-50000        0-20000        0
7973    50000-100000    20000-50000        0
4579    50000-100000  100000-200000        0
...              ...            ...      ...
9390         0-20000        0-20000        1
3244         0-20000        0-20000        1
23880        0-20000        0-20000        1
12896    20000-50000    20000-50000        1
12731  100000-200000        0-20000        0

[5415 rows x 3 columns]

In [20]:
c["success"].sum()/len(c)*100

75.08771929824562

In [21]:
# Summary 
print("With an accuracy score of", score, "our model has an relatively hight accuracy as shown in the results")
print("Accurate results:", matrix[0][0] + matrix[1][1])
print("Missed results:",  matrix[0][1] + matrix[1][0])

With an accuracy score of 0.7508771929824561 our model has an relatively hight accuracy as shown in the results
Accurate results: 3685
Missed results: 44


### Predicted Number of Sales per Genre and Price

In [22]:
# Assign values
x = s.drop(["appid", "name", "release_date", "developer", "publisher", 'required_age', 'achievements', 'positive_ratings', 'negative_ratings',
       'average_playtime', 'median_playtime', 'owners', 'linux', 'mac', 'windows', 'VR Support', 'Single-player',
       'Controller Support', 'Online', 'Multi-Player', 'co-op', 'Local'], axis=1)
y = s["owners"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# Generate the model
genre_model = LogisticRegression(max_iter=1000000).fit(X_train, y_train)

In [23]:
# Get score of the model
score = genre_model.score(X_test,y_test)

# Predict using test data
y_pred = genre_model.predict(X_test)

# Generate matrix
matrix = confusion_matrix(y_test, y_pred)

print('Accuracy score is:', score)
print('Confusion Matrix:\n',matrix)

Accuracy score is: 0.6818097876269621
Confusion Matrix:
 [[3677    2    2    0    0   20    0    0    0    6    2    0]
 [ 276    0    1    0    0    4    0    1    0    4    0    0]
 [  50    0    0    0    0    3    0    0    0    2    0    0]
 [   2    0    0    0    0    0    0    1    0    0    0    0]
 [   0    0    0    0    0    1    0    0    0    0    0    0]
 [ 617    0    0    0    0    9    0    0    0    4    1    0]
 [ 237    0    2    0    0   10    0    1    0    4    0    0]
 [  30    0    1    0    0    3    0    1    0    3    2    0]
 [   0    0    0    0    0    1    0    0    0    0    0    0]
 [ 308    0    2    0    0   10    0    0    0    5    1    0]
 [  83    0    1    0    0    4    0    4    0    2    0    0]
 [  13    0    0    0    0    0    0    2    0    0    0    0]]


In [24]:
print("With an accuracy score of", score, "our model has a medium accuracy as shown in the results")
print("Accurate results:", matrix[0][0] + matrix[1][1])
print("Missed results:",  matrix[0][1] + matrix[1][0])

With an accuracy score of 0.6818097876269621 our model has a medium accuracy as shown in the results
Accurate results: 3677
Missed results: 278


### Predicted Number of Sales per Category and Price

In [25]:
# Assign values
x = s.drop(["appid", "name", "release_date", "developer", "publisher", 'required_age', 'achievements', 'positive_ratings', 'negative_ratings',
       'average_playtime', 'median_playtime', 'owners', 'linux', 'mac', 'windows', 'Strategy', 'Free to Play', 'Sports', 'Early Access',
       'Racing', 'RPG', 'Action', 'Indie', 'Casual', 'Simulation', 'Adventure',
       'Includes level editor', 'MMO'], axis=1)
y = s["owners"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# Generate the model
category_model = LogisticRegression(max_iter=1000000).fit(X_train, y_train)

In [26]:
# Get score of the model
score = category_model.score(X_test,y_test)

# Predict using test data
y_pred = category_model.predict(X_test)

# Generate matrix
matrix = confusion_matrix(y_test, y_pred)

print('Accuracy score is:', score)
print('Confusion Matrix:\n',matrix)

Accuracy score is: 0.6932594644506002
Confusion Matrix:
 [[3754    0    1    0    0    0    0    0    0    2    0]
 [ 278    0    0    0    0    0    0    0    0    0    0]
 [  60    0    0    0    0    0    0    0    0    0    0]
 [   1    0    0    0    0    0    0    0    0    0    0]
 [   1    0    0    0    0    0    0    0    0    0    0]
 [ 567    0    0    0    0    0    0    0    0    0    0]
 [ 258    0    0    0    0    0    0    0    0    0    0]
 [  35    0    0    0    0    0    0    0    0    0    0]
 [ 357    0    0    0    0    0    0    0    0    0    0]
 [  95    0    0    0    0    0    0    0    0    0    0]
 [   6    0    0    0    0    0    0    0    0    0    0]]


In [27]:
print("With an accuracy score of", score, "our model has a medium accuracy as shown in the results")
print("Accurate results:", matrix[0][0] + matrix[1][1])
print("Missed results:",  matrix[0][1] + matrix[1][0])

With an accuracy score of 0.6932594644506002 our model has a medium accuracy as shown in the results
Accurate results: 3754
Missed results: 278


### Predicted Number of Sales per Platform and Price

In [28]:
# Assign values
x = s.drop(["appid", "name", "release_date", "developer", "publisher", 'required_age', 'achievements', 'positive_ratings', 'negative_ratings',
       'average_playtime', 'median_playtime', 'owners', 'VR Support', 'Single-player',
       'Controller Support', 'Online', 'Multi-Player', 'co-op', 'Local', 'Strategy', 'Free to Play', 'Sports', 'Early Access',
       'Racing', 'RPG', 'Action', 'Indie', 'Casual', 'Simulation', 'Adventure',
       'Includes level editor', 'MMO'], axis=1)
y = s["owners"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# Generate the model
platform_model = LogisticRegression(max_iter=1000000).fit(X_train, y_train)

In [29]:
# Get score of the model
score = platform_model.score(X_test,y_test)

# Predict using test data
y_pred = platform_model.predict(X_test)

# Generate matrix
matrix = confusion_matrix(y_test, y_pred)

print('Accuracy score is:', score)
print('Confusion Matrix:\n',matrix)

Accuracy score is: 0.6823638042474608
Confusion Matrix:
 [[3695    0    0    0    0    0    0    0    0    0    4    0    0]
 [ 291    0    0    0    0    0    0    0    0    0    0    0    0]
 [  52    0    0    0    0    0    0    0    0    0    0    0    0]
 [   6    0    0    0    0    0    0    0    0    0    0    0    0]
 [   1    0    0    0    0    0    0    0    0    0    0    0    0]
 [ 626    0    0    0    0    0    0    0    0    0    0    0    0]
 [ 243    0    0    0    0    0    0    0    0    0    0    0    0]
 [  49    0    0    0    0    0    0    0    0    0    0    0    0]
 [   2    0    0    0    0    0    0    0    0    0    0    0    0]
 [ 336    0    0    0    0    0    0    0    0    0    0    0    0]
 [ 103    0    0    0    0    0    0    0    0    0    0    0    0]
 [   6    0    0    0    0    0    0    0    0    0    0    0    0]
 [   1    0    0    0    0    0    0    0    0    0    0    0    0]]


In [30]:
print("With an accuracy score of", score, "our model has a medium accuracy as shown in the results")
print("Accurate results:", matrix[0][0] + matrix[1][1])
print("Missed results:",  matrix[0][1] + matrix[1][0])

With an accuracy score of 0.6823638042474608 our model has a medium accuracy as shown in the results
Accurate results: 3695
Missed results: 291


### Predicted Number of Sales per Genre, Category, Platform and Price

In [31]:
# Assign values
x = s.drop(["appid", "name", "release_date",'english', "developer", "publisher", 'required_age', 'achievements', 'positive_ratings', 'negative_ratings',
       'average_playtime', 'median_playtime', 'owners'], axis=1)
y = s["owners"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# Generate the model
all_model = LogisticRegression(max_iter=1000000).fit(X_train, y_train)

In [32]:
# Get score of the model
score = all_model.score(X_test,y_test)

# Predict using test data
y_pred = all_model.predict(X_test)

# Generate matrix
matrix = confusion_matrix(y_test, y_pred)

print('Accuracy score is:', score)
print('Confusion Matrix:\n',matrix)

Accuracy score is: 0.686241920590951
Confusion Matrix:
 [[3696    0    2    0   10    0    0    0    3    2    0]
 [ 275    0    0    0   10    3    3    0    3    0    0]
 [  47    0    2    0    3    1    2    0    2    2    0]
 [   3    0    0    0    0    0    2    0    1    0    0]
 [ 603    0    0    0   10    1    0    0    3    2    0]
 [ 234    0    0    0    6    1    2    0    7    4    0]
 [  33    0    1    0    3    1    0    0    2    2    0]
 [   0    0    0    0    1    0    1    0    0    0    0]
 [ 298    2    0    0    2    0    5    0    3    1    0]
 [  92    0    0    0    2    0    7    0    3    4    1]
 [   3    0    0    0    1    1    1    0    0    0    0]]


In [33]:
print("With an accuracy score of", score, "our model has a medium accuracy as shown in the results")
print("Accurate results:", matrix[0][0] + matrix[1][1])
print("Missed results:",  matrix[0][1] + matrix[1][0])

With an accuracy score of 0.686241920590951 our model has a medium accuracy as shown in the results
Accurate results: 3696
Missed results: 275


**Observations:** Similarly here, the `get_dummies` function seems to be returning interesting results that might affect my model.

### Case Study: Ubisoft
In this scenario I'm going to build a model that predicts the number of sales given a certain genre, category, platform and price, but only for games published by Ubisoft (one of the top publishers on Steam). This will hopefully produce more consistent results and a better model, since it eliminates the wide range of games that see no success despite having similar parameters.

In [34]:
# Assign values
x = s[s["publisher"]=="Ubisoft"].drop(["appid", "name", "release_date",'english', "developer", "publisher", 'required_age', 'achievements', 'positive_ratings', 'negative_ratings',
       'average_playtime', 'median_playtime', 'owners'], axis=1)
y = s[s["publisher"]=="Ubisoft"]["owners"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# Generate the model
ubisoft_model = LogisticRegression(max_iter=1000000).fit(X_train, y_train)

In [35]:
# Get score of the model
score = ubisoft_model.score(X_test,y_test)

# Predict using test data
y_pred = ubisoft_model.predict(X_test)

# Generate matrix
matrix = confusion_matrix(y_test, y_pred)

print('Accuracy score is:', score)
print('Confusion Matrix:\n',matrix)

Accuracy score is: 0.30434782608695654
Confusion Matrix:
 [[0 1 0 0 0 2 0 0 0]
 [0 0 0 0 0 5 0 0 0]
 [0 1 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 1]
 [0 1 0 0 0 1 0 0 1]]


In [36]:
print("With an accuracy score of", score, "our model has a medium accuracy as shown in the results")
print("Accurate results:", matrix[0][0] + matrix[1][1])
print("Missed results:",  matrix[0][1] + matrix[1][0])

With an accuracy score of 0.30434782608695654 our model has a medium accuracy as shown in the results
Accurate results: 0
Missed results: 1


**Observations:** I am surprised at the result. I expected the accuracy of this model to be higher, due too lower variability. However, there are only 111 games published by Ubisoft so the low number of entries might be affecting the model significantly more than anticipated. Or perhaps there's still a lot of variability among games even by the same publisher, and the low number of entris makes it even harder to make proper predictions.

In [37]:
s[s["publisher"]=="Ubisoft"]["Action"].sum()

64

## Creating a Function that Creates a Model
I'm going to change my strategy and instead of trying to create a good model that takes into account all the different features, and then pass said features to predict a result, I'm going to create a function that passes certain features and then build a specific model with those parameters. This will also make it so that the model will have significantly less variables, which is a much more suitable environement for the Logistical Regression Model to work properly.

### Predict Number of Sales based on Genre and Category

In [38]:
def logistic_regression_model(genre, category):
    # Assign values
    x = s[s[genre]==1]
    x = x[x[category]==1]
    #x = x[x["price"]==price]
    x = x.drop(["appid", "name", "release_date",'english', "developer", "publisher", 'required_age', 'achievements', 'positive_ratings', 'negative_ratings',
       'average_playtime', 'median_playtime', 'owners'], axis=1)
    y = s[s[genre]==1]
    #x = y[y["price"]==price]
    y = y[y[category]==1]["owners"]
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
    # Generate the model
    model = LogisticRegression(max_iter=1000000).fit(X_train, y_train)
    # Get score of the model
    score = model.score(X_test,y_test)
    print("Accuracy score:", round(score*100, 2), "%")
    # Predict using test data
    y_pred = model.predict(X_test)
    # Generate matrix
    matrix = confusion_matrix(y_test, y_pred)
    return list(sp.mode(y_pred)[0])[0]

#### Tests / Examples

Category and Genre options:

platforms = `'linux', 'windows', 'mac'`

genres = `'Indie', 'Sports', 'Simulation', 'Strategy', 'Early Access', 'Casual',
       'RPG', 'Free to Play', 'Adventure', 'Action', 'Racing'`
       
categories = `'Includes level editor', 'MMO', 'VR Support', 'Single-player',
       'Controller Support', 'Online', 'Multi-Player', 'co-op', 'Local'`

In [39]:
logistic_regression_model("Action", "Local")

Accuracy score: 67.75 %


'0-20000'

In [40]:
logistic_regression_model("RPG", "Online")

Accuracy score: 47.27 %


'0-20000'

####  Version 2: Goal - Improve accuracy score
The accuracy score of the previous model is not high enough, so I'm going to work on improving my model until it reaches an accuracy of around 90%. The first thing I will be trying is reducing the number of columns that I input in the model by dropping all the unecessary ones.

In [41]:
def logistic_regression_model_2(genre, category):
    # Assign values x
    x = s[s[genre]==1]
    x = x[x[category]==1]
    x.drop(["appid", "name", "release_date",'english', "developer", "publisher", 'required_age', 'achievements', 'positive_ratings',
            'negative_ratings', 'average_playtime', 'median_playtime', 'owners', "price"], axis=1, inplace=True)
    x.drop(platforms, axis=1, inplace=True)
    genres_copy = genres.copy()
    genres_copy.remove(genre)
    x.drop(genres_copy, axis=1, inplace=True)
    cat_copy = categories.copy()
    cat_copy.remove(category)
    x.drop(cat_copy, axis=1, inplace=True)
    # Assign values y
    y = s[s[genre]==1]
    y = y[y[category]==1]["owners"]
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
    # Generate the model
    model = LogisticRegression(max_iter=1000000).fit(X_train, y_train)
    # Get score of the model
    score = model.score(X_test,y_test)
    print("Accuracy score:", round(score*100, 2), "%")
    # Predict using test data
    y_pred = model.predict(X_test)
    # Generate matrix
    matrix = confusion_matrix(y_test, y_pred)
    print(matrix)
    return list(sp.mode(y_pred)[0])[0]

In [42]:
logistic_regression_model_2("Action", "Local")

Accuracy score: 68.41 %
[[1540    0    0    0    0    0    0    0    0    0    0]
 [ 105    0    0    0    0    0    0    0    0    0    0]
 [  32    0    0    0    0    0    0    0    0    0    0]
 [   4    0    0    0    0    0    0    0    0    0    0]
 [ 233    0    0    0    0    0    0    0    0    0    0]
 [ 112    0    0    0    0    0    0    0    0    0    0]
 [  19    0    0    0    0    0    0    0    0    0    0]
 [   1    0    0    0    0    0    0    0    0    0    0]
 [ 147    0    0    0    0    0    0    0    0    0    0]
 [  52    0    0    0    0    0    0    0    0    0    0]
 [   6    0    0    0    0    0    0    0    0    0    0]]


'0-20000'

In [43]:
logistic_regression_model_2("Indie", "Local")

Accuracy score: 73.39 %
[[2764    0    0    0    0    0    0    0    0]
 [ 175    0    0    0    0    0    0    0    0]
 [   8    0    0    0    0    0    0    0    0]
 [ 389    0    0    0    0    0    0    0    0]
 [ 145    0    0    0    0    0    0    0    0]
 [  18    0    0    0    0    0    0    0    0]
 [ 220    0    0    0    0    0    0    0    0]
 [  45    0    0    0    0    0    0    0    0]
 [   2    0    0    0    0    0    0    0    0]]


'0-20000'

In [44]:
logistic_regression_model_2("Indie", "Single-player")

Accuracy score: 73.89 %
[[2750    0    0    0    0    0    0    0    0]
 [ 170    0    0    0    0    0    0    0    0]
 [  18    0    0    0    0    0    0    0    0]
 [ 372    0    0    0    0    0    0    0    0]
 [ 153    0    0    0    0    0    0    0    0]
 [  12    0    0    0    0    0    0    0    0]
 [ 203    0    0    0    0    0    0    0    0]
 [  43    0    0    0    0    0    0    0    0]
 [   1    0    0    0    0    0    0    0    0]]


'0-20000'

In [45]:
logistic_regression_model_2("Free to Play", "Multi-Player")

Accuracy score: 18.59 %
[[29  0  0  0  0  0  0  0  0  0]
 [13  0  0  0  0  0  0  0  0  0]
 [ 9  0  0  0  0  0  0  0  0  0]
 [19  0  0  0  0  0  0  0  0  0]
 [31  0  0  0  0  0  0  0  0  0]
 [13  0  0  0  0  0  0  0  0  0]
 [29  0  0  0  0  0  0  0  0  0]
 [11  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0]]


'0-20000'

In [46]:
logistic_regression_model_2("Racing", "Multi-Player")

Accuracy score: 48.94 %
[[46  0  0  0  0  0]
 [ 7  0  0  0  0  0]
 [ 2  0  0  0  0  0]
 [20  0  0  0  0  0]
 [ 5  0  0  0  0  0]
 [14  0  0  0  0  0]]


'0-20000'

**Observations:** After running numerous test, my accuracy score hasn't imporved signficantly. Morevoer, I can see that the major problem I have, as shown by the confusion matrix, is that I have too many outcomes. 

What I will attempt to do is check the the amount of games that have each outcome, and reassign the ones that barely have any, and/or group together certain outcomes (number of sales).

In [47]:
s["owners"].unique()

array(['10000000-20000000', '5000000-10000000', '2000000-5000000',
       '20000000-50000000', '100000000-200000000', '50000000-100000000',
       '20000-50000', '500000-1000000', '100000-200000', '50000-100000',
       '1000000-2000000', '200000-500000', '0-20000'], dtype=object)

In [48]:
s["owners"].value_counts()

0-20000                18596
20000-50000             3059
50000-100000            1695
100000-200000           1386
200000-500000           1272
500000-1000000           513
1000000-2000000          288
2000000-5000000          193
5000000-10000000          46
10000000-20000000         21
20000000-50000000          3
50000000-100000000         2
100000000-200000000        1
Name: owners, dtype: int64

**Observations:** I can see how and why the model was always predicting that the game would receive 10000 views, it's because there's a staggering amount of games that have received that many sales. I can easily see how I can create 3 groups out of these numbers and that will reduce the number of outcomes from 13 to 3, which should give me a significantly higher accuracy, and hopefully we could sometimes obtain a prediction for something other than 10000.

Firstly however, I want to undo a step I did during the data cleaning process, which was to transform the the original sales ranges into an integer by finding the mean of each range. The data type of the target column does not matter for this type of model building so it will fit more nicely I think, to have ranges instead of specific outcomes.

#### Data Cleaning

In [49]:
s["owners"].unique()

array(['10000000-20000000', '5000000-10000000', '2000000-5000000',
       '20000000-50000000', '100000000-200000000', '50000000-100000000',
       '20000-50000', '500000-1000000', '100000-200000', '50000-100000',
       '1000000-2000000', '200000-500000', '0-20000'], dtype=object)

In [50]:
s["owners"].value_counts()

0-20000                18596
20000-50000             3059
50000-100000            1695
100000-200000           1386
200000-500000           1272
500000-1000000           513
1000000-2000000          288
2000000-5000000          193
5000000-10000000          46
10000000-20000000         21
20000000-50000000          3
50000000-100000000         2
100000000-200000000        1
Name: owners, dtype: int64

In [51]:
s["owners"].unique()

array(['10000000-20000000', '5000000-10000000', '2000000-5000000',
       '20000000-50000000', '100000000-200000000', '50000000-100000000',
       '20000-50000', '500000-1000000', '100000-200000', '50000-100000',
       '1000000-2000000', '200000-500000', '0-20000'], dtype=object)

In [52]:
def reassign_owners(row):
    a = ["20000-50000", "50000-100000", "100000-200000", "200000-500000"]
    b = ["500000-1000000", "1000000-2000000", "2000000-5000000", "5000000-10000000", "10000000-20000000", 
         "20000000-50000000", "50000000-100000000", "100000000-200000000"]
    if row in a:
        row = "20000-500000"
    elif row in b:
        row = "500000+"
    return row

In [53]:
s["owners"] = s["owners"].apply(lambda x: reassign_owners(x))

In [54]:
s["owners"].value_counts()

0-20000         18596
20000-500000     7412
500000+          1067
Name: owners, dtype: int64

#### Trying It  Again

In [55]:
logistic_regression_model_2("Action", "Local")

Accuracy score: 67.57 %
[[1521    0    0]
 [ 629    0    0]
 [ 101    0    0]]


'0-20000'

In [56]:
logistic_regression_model_2("Indie", "Local")

Accuracy score: 72.7 %
[[2738    0    0]
 [ 953    0    0]
 [  75    0    0]]


'0-20000'

In [57]:
logistic_regression_model_2("Indie", "Single-player")

Accuracy score: 73.51 %
[[2736    0    0]
 [ 916    0    0]
 [  70    0    0]]


'0-20000'

In [58]:
logistic_regression_model_2("Free to Play", "Multi-Player")

Accuracy score: 64.1 %
[[  0  22   0]
 [  0 100   0]
 [  0  34   0]]


'20000-500000'

In [59]:
logistic_regression_model_2("Racing", "Multi-Player")

Accuracy score: 50.0 %
[[47  0  0]
 [40  0  0]
 [ 7  0  0]]


'0-20000'

**Observations:** The accurancy scores haven't improved. Upon closer observation at the confusion matrixes, I observe that all the values predicted are always the same. This is due to the massive imbalance in my data set. A big majority of the games will have between 0 and 20.000 sales, which inevitably skews the predictions. 


#### Dealing with Imbalance

In order to build an accurate model that won't be determined by my data set, but will weigh the features independetly of their representaiton, I will rebalance it before running the model.

In [60]:
s["owners"].value_counts()

0-20000         18596
20000-500000     7412
500000+          1067
Name: owners, dtype: int64

In [61]:
# Deal with scaling
majority = s[s['owners'] == "0-20000"]
minority1 = s[s['owners'] == "20000-500000"]
minority2 = s[s['owners'] == "500000+"]
 
# Downsample majority class
minority1_upsampled = resample(minority1, n_samples=len(majority)) #random_state=123
minority2_upsampled = resample(minority2, n_samples=len(majority))

# Combine minority class with downsampled majority class
owners_upsampled = pd.concat([minority1_upsampled, minority2_upsampled, majority])

owners_upsampled['owners'].value_counts()

20000-500000    18596
0-20000         18596
500000+         18596
Name: owners, dtype: int64

In [62]:
def logistic_regression_model_balanced(genre, category):
    # Assign values x
    x = owners_upsampled[owners_upsampled[genre]==1]
    x = x[x[category]==1]
    x.drop(["appid", "name", "release_date",'english', "developer", "publisher", 'required_age', 'achievements', 'positive_ratings',
            'negative_ratings', 'average_playtime', 'median_playtime', 'owners', "price"], axis=1, inplace=True)
    x.drop(platforms, axis=1, inplace=True)
    genres_copy = genres.copy()
    genres_copy.remove(genre)
    x.drop(genres_copy, axis=1, inplace=True)
    cat_copy = categories.copy()
    cat_copy.remove(category)
    x.drop(cat_copy, axis=1, inplace=True)
    # Assign values y
    y = owners_upsampled[owners_upsampled[genre]==1]
    y = y[y[category]==1]["owners"]
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
    # Generate the model
    model = LogisticRegression(max_iter=1000000).fit(X_train, y_train)
    # Get score of the model
    score = model.score(X_test,y_test)
    print("Accuracy score:", round(score*100, 2), "%")
    # Predict using test data
    y_pred = model.predict(X_test)
    # Generate matrix
    matrix = confusion_matrix(y_test, y_pred)
    print(matrix)
    return list(sp.mode(y_pred)[0])[0]

#### Tests / Examples

In [63]:
logistic_regression_model_balanced("Action", "Local")

Accuracy score: 37.42 %
[[   0    0 1570]
 [   0    0 1486]
 [   0    0 1827]]


'500000+'

In [64]:
logistic_regression_model_balanced("Indie", "Local")

Accuracy score: 43.8 %
[[2774    0    0]
 [2302    0    0]
 [1257    0    0]]


'0-20000'

In [65]:
logistic_regression_model_balanced("Indie", "Single-player")

Accuracy score: 43.38 %
[[2716    0    0]
 [2297    0    0]
 [1248    0    0]]


'0-20000'

In [66]:
logistic_regression_model_balanced("Free to Play", "Multi-Player")

Accuracy score: 72.36 %
[[  0   0  32]
 [  0   0 217]
 [  0   0 652]]


'500000+'

In [67]:
logistic_regression_model_2("Racing", "Multi-Player")

Accuracy score: 58.51 %
[[55  0  0]
 [35  0  0]
 [ 4  0  0]]


'0-20000'

**Observations:** The accuracy scores have dismished despite improving the model. This further proves that the biggest issue with this model is the huge variability of the data. The sales a game recieves are simply not determined by its genre or category.

However, for the illustrative purposes of this excercise, I will use the model despite it being imperfect. 


# User-Friendly Model
I will now create an user-friendly interface that takes the user's input and build's the model according to the described specifications. 

I will also be adding visual elements to it, and possibily addind the option of having muliple genres and categories.

### Adding Data Visualization

In [68]:
def logistic_regression_model(platform, genre, category):
    # Assign values x
    x = s[s[genre]==1]
    x = x[x[category]==1]
    x.drop(["appid", "name", "release_date",'english', "developer", "publisher", 'required_age', 'achievements', 'positive_ratings',
            'negative_ratings', 'average_playtime', 'median_playtime', 'owners', "price"], axis=1, inplace=True)
    platforms_copy = platforms.copy()
    platforms_copy.remove(platform)
    x.drop(platforms_copy, axis=1, inplace=True)
    genres_copy = genres.copy()
    genres_copy.remove(genre)
    x.drop(genres_copy, axis=1, inplace=True)
    cat_copy = categories.copy()
    cat_copy.remove(category)
    x.drop(cat_copy, axis=1, inplace=True)
    # Assign values y
    y = s[s[genre]==1]
    y = y[y[category]==1]["owners"]
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
    # Generate the model
    model = LogisticRegression(max_iter=1000000).fit(X_train, y_train)
    # Get score of the model
    score = model.score(X_test,y_test)
    # Predict using test data
    y_pred = model.predict(X_test)
    # Generate matrix
    matrix = confusion_matrix(y_test, y_pred)
    print("\nThe expected amounts of sales for this game fall in the range", list(sp.mode(y_pred)[0])[0])
    print("With an accuracy score of", round(score*100, 2), "%")
    #Data Visualization
    return #plt.plot(y_pred)

### Interface

In [69]:
def model():
    print("This model will return the predicted number of sales based on key features like platform, genre, and categories.\n")
    #n = input("How many features do you want to test?")
    print("\nPlatforms:", platforms, "\n")
    platform = input("Choose Platform:\n")
    print("\nGenres:", genres, "\n")
    genre = input("Choose Genre:\n")
    print("\nCategories", categories, "\n")
    category = input("Choose Category:\n")
    result = logistic_regression_model(platform, genre, category)
    return print("\n", result)

In [70]:
model()

This model will return the predicted number of sales based on key features like platform, genre, and categories.


Platforms: ['linux', 'windows', 'mac'] 

Choose Platform:
windows

Genres: ['Indie', 'Sports', 'Simulation', 'Strategy', 'Early Access', 'Casual', 'RPG', 'Free to Play', 'Adventure', 'Action', 'Racing'] 

Choose Genre:
Action

Categories ['Includes level editor', 'MMO', 'VR Support', 'Single-player', 'Controller Support', 'Online', 'Multi-Player', 'co-op', 'Local'] 

Choose Category:
Local

The expected amounts of sales for this game fall in the range 0-20000
With an accuracy score of 67.88 %

 None


**Observations:** I am happy with the current model, despite its questionable accuracy. However, I still want to take a shot at improving it in the following ways:

1. Making the target binary. Even if this will reduce the usefulness of the result, it will improve the overall performance of the model.
2. Attempting to include developer or publisher in the features being tested. This wasn't done from the start because the unique variables in these categories is unsurmountable high. However, simply by dividing both in 2 groups (more than 10 games vs less than 10 games, for example) could improve the model since developer and publisher do have a significant effect on sales.
3. Try a different model altogether, potentially better fitted for this situation. Namely a Decision Tree.

### Binary
I will be using an upsampling technique to balance out the target data. I will devide this one in 2 groups, `0-20000` and `20000+`.

In [71]:
s["owners"].value_counts()

0-20000         18596
20000-500000     7412
500000+          1067
Name: owners, dtype: int64

In [72]:
def reassign_owners_binary(row):
    a = ["20000-50000", "50000-100000", "100000-200000", "200000-500000"]
    b = ["500000-1000000", "1000000-2000000", "2000000-5000000", "5000000-10000000", "10000000-20000000", 
         "20000000-50000000", "50000000-100000000", "100000000-200000000"]
    if row in a:
        row = "20000+"
    elif row in b:
        row = "20000+"
    return row

In [73]:
s["owners"] = s["owners"].apply(lambda x: reassign_owners_binary(x))

In [74]:
s["owners"].value_counts()

0-20000         18596
20000-500000     7412
500000+          1067
Name: owners, dtype: int64

In [75]:
# Deal with scaling
majority = s[s['owners'] == "0-20000"]
minority = s[s['owners'] == "20000+"]
 
# Downsample majority class
minority_upsampled = resample(minority, n_samples=len(majority)) #random_state=123

# Combine minority class with downsampled majority class
owners_upsampled_binary = pd.concat([minority_upsampled, majority])

owners_upsampled_binary['owners'].value_counts()

ValueError: low >= high

In [ ]:
def logistic_regression_model_binary(platform, genre, category):
    # Assign values x
    x = owners_upsampled_binary[owners_upsampled_binary[genre]==1]
    x = x[x[category]==1]
    x.drop(["appid", "name", "release_date",'english', "developer", "publisher", 'required_age', 'achievements', 'positive_ratings',
            'negative_ratings', 'average_playtime', 'median_playtime', 'owners', "price"], axis=1, inplace=True)
    platforms_copy = platforms.copy()
    platforms_copy.remove(platform)
    x.drop(platforms_copy, axis=1, inplace=True)
    genres_copy = genres.copy()
    genres_copy.remove(genre)
    x.drop(genres_copy, axis=1, inplace=True)
    cat_copy = categories.copy()
    cat_copy.remove(category)
    x.drop(cat_copy, axis=1, inplace=True)
    # Assign values y
    y = owners_upsampled_binary[owners_upsampled_binary[genre]==1]
    y = y[y[category]==1]["owners"]
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
    # Generate the model
    model = LogisticRegression(max_iter=1000000).fit(X_train, y_train)
    # Get score of the model
    score = model.score(X_test,y_test)
    # Predict using test data
    y_pred = model.predict(X_test)
    # Generate matrix
    matrix = confusion_matrix(y_test, y_pred)
    print("\nThe expected amounts of sales for this game fall in the range", list(sp.mode(y_pred)[0])[0])
    print("With an accuracy score of", round(score*100, 2), "%")
    #Data Visualization
    return 

In [ ]:
def model_binary():
    print("This model will return the predicted number of sales based on key features like platform, genre, and categories.\n")
    #n = input("How many features do you want to test?")
    print("\nPlatforms:", platforms, "\n")
    platform = input("Choose Platform:\n")
    print("\nGenres:", genres, "\n")
    genre = input("Choose Genre:\n")
    print("\nCategories", categories, "\n")
    category = input("Choose Category:\n")
    result = logistic_regression_model_binary(platform, genre, category)
    return print("\n", result)

In [ ]:
model_binary()

**Observations:** The accuracy hasn't improved much, and I still can't manage to include a visualization. Underwhelming success.

### Include Developer and Publisher in the Model
In order to do this, I first have to divide each category in 2 groups. Thus I'm first going to explore the data to decide where I should make the division.

In [ ]:
s.head(1)

In [ ]:
s["developer"].value_counts()[:10]

In [ ]:
dev_count = s["developer"].value_counts()
len(dev_count[dev_count>9])/len(dev_count)*100

**Observations:** After trying different options I decide that separating developers by those that have made more than 3 games and the rest seems a good split. My top developors now represent only 5% of my data. I might play with this number in the future. Potentially try it when it represents only 1% of the developers and thus have a clear "1% has it all" model.

In [ ]:
s["top_developer"] = 0
values = dev_count[dev_count>19].index.tolist()

for w in values:
    for i in range(len(s)):
        if w in s["developer"][i]:
            s["top_developer"][i] = 1
            
s["top_developer"].value_counts()

In [ ]:
s["publisher"].value_counts()[:10]

In [ ]:
dev_count = s["publisher"].value_counts()
len(dev_count[dev_count>16])/len(dev_count)*100

In [ ]:
s["top_publisher"] = 0
values = dev_count[dev_count>49].index.tolist()

for w in values:
    for i in range(len(s)):
        if w in s["publisher"][i]:
            s["top_publisher"][i] = 1
            
s["top_publisher"].value_counts()

### Adjusting the Model

In [ ]:
def logistic_regression_model_full(platform, genre, category, developer, publisher):
    # Assign values x
    x = s[s[genre]==1]
    x = x[x[category]==1]
    x = x[x[platform]==1]
    if developer == "yes":
        x = x[x["top_developer"]==1]
    else:
        x = x[x["top_developer"]==0]
    if publisher == "yes":
        x = x[x["top_publisher"]==1]
    else:
        x = x[x["top_publisher"]==0]
    x.drop(["appid", "name", "release_date",'english', "developer", "publisher", 'required_age', 'achievements', 'positive_ratings',
            'negative_ratings', 'average_playtime', 'median_playtime', 'owners', "price"], axis=1, inplace=True)
    platforms_copy = platforms.copy()
    platforms_copy.remove(platform)
    x.drop(platforms_copy, axis=1, inplace=True)
    genres_copy = genres.copy()
    genres_copy.remove(genre)
    x.drop(genres_copy, axis=1, inplace=True)
    cat_copy = categories.copy()
    cat_copy.remove(category)
    x.drop(cat_copy, axis=1, inplace=True)
    # Assign values y
    y = s[s[genre]==1]
    y = y[y[category]==1]
    y = y[y[platform]==1]
    if developer == "yes":
        y = y[y["top_developer"]==1]
    else:
        y = y[y["top_developer"]==0]
    if publisher == "yes":
        y = y[y["top_publisher"]==1]
    else:
        y = y[y["top_publisher"]==0]
    y = y["owners"]
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
    # Generate the model
    model = LogisticRegression(max_iter=1000000).fit(X_train, y_train)
    # Get score of the model
    score = model.score(X_test,y_test)
    # Predict using test data
    y_pred = model.predict(X_test)
    # Generate matrix
    matrix = confusion_matrix(y_test, y_pred)
    print("\nThe expected amounts of sales for this game fall in the range", list(sp.mode(y_pred)[0])[0])
    print("With an accuracy score of", round(score*100, 2), "%")
    #Data Visualization
    return #plt.plot(y_pred)

In [ ]:
def model_full():
    print("This model will return the predicted number of sales based on key features like platform, genre, and categories.\n")
    #n = input("How many features do you want to test?")
    print("\nPlatforms:", platforms, "\n")
    platform = input("Choose Platform:\n")
    print("\nGenres:", genres, "\n")
    genre = input("Choose Genre:\n")
    print("\nCategories", categories, "\n")
    category = input("Choose Category:\n")
    developer = input("Has the developer developed 20 games or more?")
    publisher = input("Has the publisher published 50 games or more?")
    result = logistic_regression_model_full(platform, genre, category, developer, publisher)
    return print("\n", result)

In [ ]:
model_full()

**Observations:** I don't see a significant improvement but I can at least feel that my model is more complete. This is as far as I'm going to go improving this given model.

### Data Visualization

In [ ]:
from sklearn import metrics
 
y_pred_proba = model.predict_proba(X_test)[::,1]
fpr, tpr, _ = metrics.roc_curve(y_test,  y_pred_proba)
auc_lr = metrics.roc_auc_score(y_test, y_pred_proba)
 
plt.plot(fpr,tpr)

In [ ]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
logit_roc_auc = roc_auc_score(y_test, log_model.predict(X_test))
fpr, tpr, thresholds = roc_curve(y_test, model.predict_proba(X_test)[:,1])
plt.figure()
plt.plot(fpr, tpr, label='Logistic Regression (area = %0.2f)' % logit_roc_auc)
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic')
plt.legend(loc="lower right")
plt.savefig('Log_ROC')
plt.show()